Fix cpp headers and libraries installation when using setup.py
onnx/onnx pull request #3077
Opened 2020-10-28 13:02 UTC by AnthonyBarbier

- Some of the generated protobuf headers were missing
- None of the shared libraries were packaged
- The CMake targets were missing.

The aim of this patch is to fix the Conda package so that it can be used to build user applications.
Unfortunately I don't know much about Conda so I haven't been able to generate a new package.

2020-10-28 13:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/onnx/onnx?pullRequest=3077) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/onnx/onnx?pullRequest=3077) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/onnx/onnx?pullRequest=3077) it.</sub>

2020-10-28 15:15 UTC, jcwchen requested changes

2020-10-28 15:15 UTC, jcwchen commented on setup.py
> +        self.copy_tree(os.path.join(CMAKE_BUILD_DIR,"install","lib"),
```suggestion
        self.copy_tree(os.path.join(CMAKE_BUILD_DIR, "install", "lib"),
```
Add a space after , to meet flake8. L225 needs the same fix.

2020-10-28 15:18 UTC, jcwchen commented
Thank you for proposing this PR. 
Questions: Are you saying it's a conda-specific bug? Is PyPi related to this?

2020-10-28 15:43 UTC, AnthonyBarbier commented
It's a bug related to all the packages generated using `setuptools.py` (Only the pure CMake build seems to be installing all the files as expected).
Which means the `pip install` / `setuptools.py` or `conda` packages all have the problem

2020-10-30 18:18 UTC, AnthonyBarbier commented
Is the circleci supposed to pass ? Pybind11 seems to be missing ?

2020-10-31 14:17 UTC, jcwchen commented
> Is the circleci supposed to pass ? Pybind11 seems to be missing ?

circleci will be deprecated so you can just ignore it.

BTW, currently I am releasing ONNX 1.8.0, typically we will remove those produced .pb during release process: https://github.com/onnx/onnx/blob/master/docs/OnnxReleases.md
I guess the reason is these .pb files will be protobuf sensitive. For instance, if the wheel built with newer protobuf, these .pb files would possibly not work with older protobuf, and vice versa. Therefore, as library's prospective, onnx won't release anything has strict protobuf dependency since the document does not mention any specific protobuf requirement. If users want to use these .pb files, they will need to build on their own based on their protobuf version.

Does it make sense to you? Thanks.

2020-10-31 16:01 UTC, AnthonyBarbier commented
> > Is the circleci supposed to pass ? Pybind11 seems to be missing ?
> 
> circleci will be deprecated so you can just ignore it.
> 
> BTW, currently I am releasing ONNX 1.8.0, typically we won't upload those produced .pb during release process.
> I guess the reason is these .pb files will be protobuf sensitive. For instance, if the wheel built with newer protobuf, these .pb files would possibly not work with older protobuf, and vice versa. Therefore, as library's prospective, onnx won't release anything has strict protobuf dependency since the document does not mention any specific protobuf requirement. If users want to use these .pb files, they will need to build on their own based on their protobuf version.
> 
> Does it make sense to you? Thanks.

You should make sure that none of the public headers include any of these pb files then: as it stands the library you distribute is pretty useless as the public headers keep having missing includes which means the user actually needs to rebuild them, unless I'm missing something ?

2020-10-31 16:13 UTC, AnthonyBarbier commented
The.pb.cc is compiled in the onnx library, so whatever you distribute already depends on a specific version of protobuf, no?

2020-10-31 23:06 UTC, jcwchen commented
To clarify: I am releasing ONNX 1.8.0 "PyPI" Package. And yes, it will depend on certain protobuf version, but we will do our best effort to make sure the built Python API supports backward and forward compatibility of protobuf. By contrast, these header files are more like intermediate files and won't be included in the Python package because we cannot guarantee whether these produced C++ headers from the release pipeline support backward and forward compatibility for protobuf.

If any user is interested in using ONNX through C/C++, they can generate these headers from source (under .setuptools-cmake-build/onnx) based on their local protoc, which is more compatible for them to use in their environments.

2020-10-31 23:47 UTC, AnthonyBarbier commented
Just for context: we only use the schema.h to let the users define their own custom op.
I just want a way for the user to have access to it without having to faff with building onnx or protobuf. 
Ideally just using Conda. It doesn't have to be python, I'm only interested in them being able to access the cpp interface

2020-11-01 11:44 UTC, AnthonyBarbier commented
Here is an example: https://github.com/graphcore/popart/blob/sdk-release-1.3/examples/custom_ops/custom_op.cpp#L43
Basically the op is built as a standalone shared library that python will then `dlopen`.

2020-11-09 17:01 UTC, AnthonyBarbier commented
FYI in the end I've created a separate Conda recipe to package only the C++ library https://github.com/conda-forge/staged-recipes/pull/13108

Cc @ezyang @marcelotrevisani

2020-11-10 15:59 UTC, jcwchen commented
Sorry for the late reply because I was busy with ONNX 1.8 Release...
I believe conda package is a better scenario for using ONNX through C/C++ because the protobuf version in conda would be fixed. @AnthonyBarbier Thank you so much for the contribution in conda-forge!

2023-02-22 06:43 UTC, closed without merging