[WIP] Segfault fix test
onnx/onnx pull request #3094
Opened 2020-11-04 22:23 UTC by askhade

Signed-off-by: Ashwini Khade <askhade@microsoft.com>

2020-11-05 03:32 UTC, jcwchen requested changes

2020-11-05 03:32 UTC, jcwchen commented on .github/workflows/debug_win.yml
> +        cmake -G "Visual Studio 16 2019" -A $arch -DCMAKE_INSTALL_PREFIX="../../protobuf_install" -DCMAKE_BUILD_TYPE=Release -Dprotobuf_MSVC_STATIC_RUNTIME=ON -DProtobuf_USE_STATIC_LIBS=ON -Dprotobuf
```suggestion
        cmake -A $arch -DCMAKE_INSTALL_PREFIX="../../protobuf_install" -DCMAKE_BUILD_TYPE=Release -Dprotobuf_MSVC_STATIC_RUNTIME=ON -DProtobuf_USE_STATIC_LIBS=ON -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_BUILD_EXAMPLES=OFF .
```

2020-11-05 03:32 UTC, jcwchen commented on .github/workflows/debug_win.yml
> +        cmake -G "Visual Studio 16 2019" -A $arch -DCMAKE_INSTALL_PREFIX="../../protobuf_install" -DCMAKE_BUILD_TYPE=Release -Dprotobuf_MSVC_STATIC_RUNTIME=ON -DProtobuf_USE_STATIC_LIBS=ON -Dprotobuf
Don't forget to remove 2019.  Also for release_win.yml

2020-11-07 18:52 UTC, closed without merging

2020-11-07 18:53 UTC, askhade commented
This was to test some fixes for the segfault which we were seeing when exception are thrown from infer shapes mtd. The solution was to update the version of pybind11