Add weekly CI: provide ONNX TestPyPI packages for verification
onnx/onnx pull request #3283
Opened 2021-02-18 18:39 UTC by jcwchen

**Description**
Add a weekly (or nightly) CI to automatically produce and upload  TestPyPI packages.

**Motivation**
To enhance robustness, provide a TestPyPI package for partners (e.g., ORT, tesorflow-onnx) to often verify ONNX.

2021-03-06 01:03 UTC, askhade commented
2 comments:
1. Use the release CIs instead of creating a new workflow
2. We need this for all platforms not just windows

2021-03-06 04:58 UTC, jcwchen commented
> 2 comments:
> 
> 1. Use the release CIs instead of creating a new workflow
> 2. We need this for all platforms not just windows

Updated. Thanks for the suggestions

2021-03-08 17:25 UTC, askhade commented on setup.py
> +    if '--weekly_build' in sys.argv:
where is this arg passed to setup.py... I dont see it in any yamls

2021-03-08 17:27 UTC, askhade commented on .github/workflows/release_win.yml
> +    - name: Upload wheel to TestPyPI
Looks like this step will run on every CI run. We want to upload only for weekly jobs not for push and pull request runs

2021-03-08 17:27 UTC, askhade commented on .github/workflows/release_mac.yml
> +    - name: Upload wheel to TestPyPI
same comment as below for all yamls... this step should only run for weekly job

2021-03-08 17:28 UTC, askhade requested changes
comments added

2021-03-12 18:40 UTC, jcwchen commented
Updated. I have tested it in my forked repo and onnx-weekly wheel can be produced correctly. This PR is ready for review again. Thanks

2021-03-16 17:46 UTC, jcwchen commented
Thanks @prasanthpul for adding TestPyPI credentials

2021-03-17 16:54 UTC, askhade approved these changes

2021-03-18 15:35 UTC, merged