Update BatchNorm to specify population variance
onnx/onnx pull request #3402
Opened 2021-04-06 23:47 UTC by neginraoof

Update BatchNorm to specify population variance.

Signed-off-by: neginraoof <neginmr@utexas.edu>

2021-04-07 04:49 UTC, askhade approved these changes

2021-04-07 15:25 UTC, jcwchen approved these changes
The updated .onnx testdata is good @onnx/sig-operators-approvers please forward it. Thanks.

2021-04-07 16:55 UTC, jcwchen commented on docs/Changelog.md
> +  where N is the population size (this formula does not use sample size N - 1).
Don't forget to consider the comment here: https://github.com/onnx/onnx/pull/3406#discussion_r608826460

2021-04-07 22:01 UTC, gramalingam approved these changes

2021-04-09 05:33 UTC, SherlockNoMad commented
During mixed precision training, input_mean, input_var and running_mean and running_var are usually kept in fp32, while X and Y can be in fp16.

see https://docs.nvidia.com/deeplearning/performance/mixed-precision-training/index.html#lossscaling 

We need to introduce a different type for input_mean, input_var and running_mean and running_var.

2021-04-09 05:34 UTC, SherlockNoMad requested changes
need a new type for input_mean, input_var and running_mean and running_var

2021-04-09 15:34 UTC, merged

2021-04-09 15:35 UTC, askhade commented
The corresponding cherry pick change has been already checked in release branch so we should not make any more changes to this PR... any changes should be made in a new PR