Remove unused test data
onnx/onnx pull request #3581
Opened 2021-07-14 21:57 UTC by neginraoof

Signed-off-by: neginraoof <neginmr@utexas.edu>

**Description**
Removing unused test model and data

2021-07-14 22:01 UTC, gramalingam approved these changes

2021-07-14 22:10 UTC, askhade approved these changes

2021-07-14 23:00 UTC, jcwchen requested changes
Please note that there are other errors:
```
test_cast_FLOAT_to_BFLOAT16 failed: Field 'shape' of type is required but missing.
test_loop13_seq failed: Field 'shape' of type is required but missing.
test_castlike_BFLOAT16_to_FLOAT failed: Field 'shape' of type is required but missing.
test_cast_BFLOAT16_to_FLOAT failed: Field 'shape' of type is required but missing.
test_castlike_FLOAT_to_BFLOAT16 failed: Field 'shape' of type is required but missing.
test_castlike_FLOAT_to_BFLOAT16_expanded failed: Field 'shape' of type is required but missing.
test_castlike_BFLOAT16_to_FLOAT_expanded failed: Field 'shape' of type is required but missing.
```
It only happened with generated test data so test scripts for the models above might need to be updated. Uploaded model files should be fine in this case. Thanks for the fix

2021-07-14 23:54 UTC, neginraoof commented
@askhade  I am addressing the failures on the CI. Will update as soon as this is resolved.

2021-07-15 00:15 UTC, neginraoof commented
@askhade The CI looks green now. Can you take a look? Thanks a lot.

2021-07-15 00:27 UTC, jcwchen approved these changes

2021-07-15 03:43 UTC, merged