Fix If tests
onnx/onnx pull request #3707
Opened 2021-09-08 00:34 UTC by neginraoof

Signed-off-by: neginraoof <neginmr@utexas.edu>

**Description**
Fix test data for if_optional tests

2021-09-08 16:56 UTC, jcwchen commented
Thanks for proposing the fix. Reopen this PR to trigger Release CIs.

2021-09-09 00:31 UTC, jcwchen approved these changes

2021-09-09 05:09 UTC, neginraoof commented
Thanks @jcwchen for review. Please let me know if we can merge this PR.
+ @askhade 

Thanks

2021-09-09 19:02 UTC, askhade requested changes
nit: some typos

2021-09-09 20:17 UTC, askhade approved these changes

2021-09-09 20:52 UTC, merged