Bump release version to 1.13
onnx/onnx pull request #4666
Opened 2022-11-18 11:51 UTC by p-wysocki

Signed-off-by: p-wysocki <przemyslaw.wysocki@intel.com>

### Description
PR is a part of an ongoing 1.13.0 release. It's based on https://github.com/onnx/onnx/pull/4209.

2022-11-18 17:28 UTC, jcwchen reviewed
The PR itself looks good to me. Will approve it after code freeze. Thank you @p-wysocki for driving ONNX 1.13 release!

2022-11-22 17:08 UTC, liqunfu requested changes

2022-11-22 17:15 UTC, liqunfu reviewed
also need to make change to https://github.com/onnx/onnx/blob/main/VERSION_NUMBER

2022-11-22 17:19 UTC, liqunfu approved these changes

2022-11-22 17:20 UTC, jcwchen approved these changes

2022-11-22 17:41 UTC, gramalingam approved these changes

2022-11-22 17:46 UTC, p-wysocki commented
@liqunfu Do you mean https://github.com/onnx/onnx/pull/4666/files#diff-22aa3cdc2dc9bec750e99a529ea7ac3d2642c71212cb3d8843265916ea7ffc18L1? That file has been changed.

2022-11-22 19:45 UTC, merged