Update working-groups.md
onnx/onnx pull request #4853
Opened 2023-02-06 11:39 UTC by andife

Signed-off-by: Andreas Fehlner <fehlner@arcor.de>

### Description

### Motivation and Context

2023-02-06 16:53 UTC, prasanthpul approved these changes

2023-02-06 16:54 UTC, prasanthpul commented on community/working-groups.md
> +You can find the schedule of meetings on the [LF AI wiki](https://onnx.ai/calender)
typo: calendar

2023-02-06 16:55 UTC, prasanthpul requested changes
typo breaks url

2023-02-06 17:15 UTC, andife commented on community/working-groups.md
> +You can find the schedule of meetings on the [LF AI wiki](https://onnx.ai/calender)
fixed

2023-02-07 00:13 UTC, gramalingam approved these changes

2023-02-09 10:29 UTC, xadupre approved these changes

2023-02-10 18:16 UTC, prasanthpul approved these changes

2023-02-10 19:18 UTC, merged