Remove external file if exists in extract_model
onnx/onnx pull request #6497
Opened 2024-10-27 06:12 UTC by tonypottera24

### Description

Remove the external file if exists on `onnx.save`.

### Motivation and Context

If the external file is not removed, it will not be overwritten. The new content is always appended to it, making it larger and larger forever.

2024-10-28 10:43 UTC, xadupre commented
Should we remove it or raise an exception?

2024-10-28 17:38 UTC, tonypottera24 commented
> Should we remove it or raise an exception? cc @gramalingam

Should I do this here or inside `onnx.save`?

2024-10-30 04:15 UTC, justinchuby commented
I think we should overwrite, but I am not sure if that is entirely robust either: I can imagine when part of the tensors are external in the model pointing to `model.data`, after calling save(), if we overwrite, the original external data would be gone so the original references will be invalid and get undetected (silent incorrectness).

However if we raise, the user will then need to manually remove the data file. This is `O(# tensors)` and quite burdensome in the case when `all_tensors_to_one_file` is false because there would be many files.

The current behavior of appending is actually the only safe way I can think of, but admittedly not optimal as explained in this PR.

2024-10-30 04:19 UTC, justinchuby approved these changes
LGTM thanks. Please ignore my previous comments

2024-10-30 04:20 UTC, justinchuby commented
Could you add the `Raises` section in the docstring to describe this new behavior. Thanks! ref: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

2024-10-30 04:23 UTC, justinchuby commented
Overwriting can be unsafe if the model proto has reference to the existing data file. Maybe we can provide an option? But I also don't prefer overcrowding the options we have. hmm

2024-10-30 04:23 UTC, justinchuby requested changes
Deferring to @gramalingam

2024-10-30 04:29 UTC, tonypottera24 commented
> Could you add the `Raises` section in the docstring to describe this new behavior. Thanks! ref: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

Thank you @justinchuby, I added the explanations.

2024-10-30 05:23 UTC, tonypottera24 commented
I saw `offset` in function `save_external_data`...

2024-11-21 17:25 UTC, gramalingam commented
I think it is safer not to overwrite it silently. I am fine with using a user option to overwrite or leaving in the PR's current form (with an exception).

2024-11-21 17:28 UTC, justinchuby commented on onnx/external_data_helper.py
> +                raise FileExistsError(f"File exists in {location}.")
```suggestion
                raise FileExistsError(f"External file exists in {location}.")
```

2024-11-21 17:29 UTC, justinchuby commented on onnx/external_data_helper.py
> +                raise FileExistsError(f"External file exists in {location}.")
```suggestion
                raise FileExistsError(f"External data file exists in {location}.")
```

2024-11-21 17:29 UTC, justinchuby approved these changes

2024-11-21 18:09 UTC, merged